### ISSUE TITLE
Rewards with Red Cross

### ISSUE THREAD

**Issue by kalinzange** [LeagueOfPoro/EsportsCapsuleFarmer#21]
Hi,

Since the video's release, I've been using your program for the Capsule Farm. Works Great! My only suggestion is to store cookies/cache so I avoid consistently placing the 2FA from Riot.

Sometimes, as I've noticed, when I go check the streams I notice there's a red cross on the rewards. I have to manually refresh the stream and see if the red cross changes to the checkmark. I'm not sure if you can add a check and make the tab refresh to see if the rewards are actually with that checkmark or not, but would be great as some games start at 01-03 AM in my timezone leading to 8h of the possibility of not receiving any of the rewards.
![image](https://user-images.githubusercontent.com/38161086/178696251-eacfae74-9d20-419b-9c17-a9009cc31038.png)

Thank You.

**Comment by JonasTD** [comment]
Sometimes another streaming platform besides twitch or youtube is selected, in most of those cases no rewards are given in general.
I assume you refreshing means it selects another provider (twitch or youtube) and thus makes you eligable for rewards.
This issue is related to the esports website itself & not the capsule farmer program.

**Comment by LeagueOfPoro** [comment]
The program tries to go directly to the page with the Twitch broadcast. The list is probably not complete but it should force Twitch in most cases

```python
# Force Twitch player
OVERRIDDES = {
    "https://lolesports.com/live/lck_challengers_league":"https://lolesports.com/live/lck_challengers_league/lckcl",
    "https://lolesports.com/live/lpl":"https://lolesports.com/live/lpl/lpl",
    "https://lolesports.com/live/lck":"https://lolesports.com/live/lck/lck",
    "https://lolesports.com/live/lec":"https://lolesports.com/live/lec/lec",
    "https://lolesports.com/live/lcs":"https://lolesports.com/live/lcs/lcs",
    "https://lolesports.com/live/lco":"https://lolesports.com/live/lco/lco",
    "https://lolesports.com/live/cblol_academy":"https://lolesports.com/live/cblol_academy/cblol",
    "https://lolesports.com/live/cblol":"https://lolesports.com/live/cblol/cblol",
    "https://lolesports.com/live/lla":"https://lolesports.com/live/lla/lla"
}
```

**Comment by kalinzange** [comment]
> I assume you refreshing means it selects another provider (twitch or youtube) and thus makes you eligable for rewards.

Actually refreshing the page of the stream, not the platform I'm watching from

**Comment by TheFeelTrain** [comment]
I have the same issue, it has nothing to do with the overrides, sometimes it just doesn't work until you refresh for one reason or another.

**Comment by LeagueOfPoro** [comment]
I will add the rewards check to the next version

**Comment by LeagueOfPoro** [comment]
Fixed in 3.0

**Comment by kalinzange** [comment]
> Fixed in 3.0

![image](https://user-images.githubusercontent.com/38161086/181051078-f57739b4-2a25-41d1-9417-13ee87090313.png)
Still not 100% Fixed, I'd recommend performing a run of the eligibility of rewards of existing/open matches when trying to find the new matches every 10 minutes, otherwise the effect of this fix will be lifted

**Comment by TheFeelTrain** [comment]
I just realized I didn't add any context with my previous comment. The stream will open fine but can occasionally *lose* the checkmark and needs to be manually refreshed. I was also hoping it would check through all of the currently running games but that is my bad for not explaining it very well.

**Comment by LeagueOfPoro** [comment]
> I was also hoping it would check through all of the currently running games but that is my bad for not explaining it very well.

Added in the latest version
